baseURL = "https://blog.fortruce.com/"
languageCode = "en-us"
title = "fortruce"
theme = "hugo-theme-tokiwa"

[params]
description = """
bits and pieces
"""
mainSections = ["posts"]
useChineseFonts = false
postDateFormat = "2006-1-2"

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "/tags/"
weight = 1

[[menu.main]]
identifier = "Categories"
name = "Categories"
url = "/categories/"
weight = 2
